# Generated by Django 5.0.1 on 2024-01-27 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='petphoto',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
