# Generated by Django 5.0.1 on 2024-01-27 12:20

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_petphoto_created_on_petphoto_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[petstagram.photos.validators.validate_photo_size]),
        ),
    ]
