# Generated by Django 5.0.1 on 2024-02-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0007_alter_petphoto_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='photos.petphoto'),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='photos.petphoto'),
        ),
    ]
